apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.network.ingress.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: {{ .Values.network.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.network.service.name }}
            port:
              number: {{ .Values.network.service.port }}
      - path: /homepage/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.network.service.name }}
            port:
              number: {{ .Values.network.service.port }}
