apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.role.adminRole }}
  namespace: {{ .Values.homework }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccount.adminAccount }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.role.monitoringRole }}
  namespace: {{ .Values.homework }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccount.monitoringAccount }}
  namespace: {{ .Values.homework }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.role.monitoringRole }}
  apiGroup: rbac.authorization.k8s.io
