apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.network.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.deployment.labels }}
  ports:
    - protocol: TCP
      port: {{ .Values.network.service.port }}
      targetPort: {{ .Values.network.service.targetPort }}
      name: {{ .Values.network.service.portName }}
