apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccount.adminAccount }} 
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccount.monitoringAccount }}
  namespace: {{ .Values.namespace }}
