apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: endpoint-monitoring 
  namespace: homework
subjects:
- kind: ServiceAccount
  name: monitoring
  namespace: homework
roleRef:
  kind: Role
  name: endpoint-monitoring
  apiGroup: rbac.authorization.k8s.io
