apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: server
        image: tomyork1986/simple-web-server:1.1.0
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/"
            port: 8000
            httpHeaders:
            - name: "Cookie"
              value: "shop_session-id=x-readiness-probe"
