apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: payment-service
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: tomyork1986/payment-service:0.0.1
