apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: homework
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: web-port
